"""Vision model loading and image processing utilities for Agri-Scan."""

from io import BytesIO
from pathlib import Path
from typing import List, Tuple

import numpy as np
import streamlit as st
from PIL import Image
from ultralytics import YOLO


MODEL_PATH = Path(__file__).resolve().parent / "assets" / "best.pt"


@st.cache_resource
def load_vision_model() -> YOLO:
    """Load the agricultural YOLO model from the canonical assets path.

    Fails safely (stops the app) if the required model file is missing.
    """
    if not MODEL_PATH.exists():
        st.error(
            "❌ Core agricultural model is missing. "
            f"Expected file at: {MODEL_PATH}"
        )
        st.stop()

    return YOLO(str(MODEL_PATH))


def process_image(model: YOLO, uploaded_file) -> Tuple[List[Tuple[str, float]], np.ndarray]:
    """Run YOLO inference on uploaded image and return detections + annotated frame.

    Returns:
        detections: list of (class_name, confidence) tuples.
        annotated_image: numpy array generated by Ultralytics `plot()`.
    """
    image_bytes = uploaded_file.getvalue() if hasattr(uploaded_file, "getvalue") else uploaded_file.read()
    image = Image.open(BytesIO(image_bytes)).convert("RGB")

    results = model.predict(image, save=False, verbose=False)
    result = results[0]

    detections: List[Tuple[str, float]] = []
    for box in result.boxes:
        cls_id = int(box.cls[0])
        confidence = float(box.conf[0])
        class_name = model.names[cls_id]
        detections.append((class_name, confidence))

    annotated_image = result.plot()
    return detections, annotated_image


# Backward-compatible alias for existing imports
load_model = load_vision_model
